# Generated by Django 4.2 on 2025-07-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tvshow', 'TV Show')], default='movie', max_length=10),
        ),
    ]
