# Generated by Django 4.2 on 2025-07-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_movie_episodes_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='episodes_watched',
            field=models.IntegerField(null=True),
        ),
    ]
